name: First Interaction

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome! Thanks for opening your first issue."
          pr-message: "Welcome! Thanks for your first pull request."
