name: Lock Closed Issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lock:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@v6
        with:
          issue-inactive-days: 30
          pr-inactive-days: 30
