name: Todo to Issue

on:
  push:
    branches: [main]

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v7
      - uses: alstr/todo-to-issue-action@v5
        with:
          AUTO_ASSIGN: true
